const productos = [
    {nombre: "Samsung Galaxy S23 Ultra 512GB", 
     color: "Blanco",
     id: 1, 
     precio: 459000, 
     img: "./images/s23.png",
     cantidad: 1,
     categoria: "Celulares"},

    {nombre: "Apple IPhone 11 Pro Max 64 GB", 
     color: "Oro",
     id: 2, 
     precio: 370000, 
     img: "./images/iphone-11-pro.jpg",
     cantidad: 1,
     categoria: "Celulares"},

    {nombre: "Motorola Moto G52 128GB", 
     color: "Azul",
     id: 3, 
     precio: 120000, 
     img: "./images/moto-g52.jpg",
     cantidad: 1,
     categoria: "Celulares"},

    {nombre: "Apple IPhone 13 128GB", 
     color: "Rosa",
     id: 4, 
     precio: 420000, 
     img: "./images/iphone-13.jpg",
     cantidad: 1,
     categoria: "Celulares"},

    {nombre: "Auriculares inalámbricos Samsung", 
     color: "Lila",
     id: 5, 
     precio: 39500, 
     img: "./images/auri-samsung.jpg",
     cantidad: 1,
     categoria: "Auriculares"},

    {nombre: "Apple AirPods con estuche de carga", 
     color: "Blanco",
     id: 6, 
     precio: 47500, 
     img: "./images/airpods.jpg",
     cantidad: 1,
     categoria: "Auriculares"},
    
    {nombre: "Apple Watch SE GPS", 
     color: "Oro",
     id: 7, 
     precio: 137000, 
     img: "./images/apple-watch.jpg",
     cantidad: 1,
     categoria: "Relojes"},
    
    {nombre: "Samsung Galaxy Watch4 (Bluetooth)", 
     color: "Rosa oro",
     id: 8, 
     precio: 95000, 
     img: "./images/smart-watch.jpg",
     cantidad: 1,
     categoria: "Relojes"},

    {nombre: "Auriculares inalambricos JBL", 
     color: "Celeste",
     id: 9, 
     precio: 12500, 
     img: "./images/jbl-auri.jpg",
     cantidad: 1,
     categoria: "Auriculares"},

    {nombre: "Auriculares inalambricos Daewoo", 
     color: "Verde",
     id: 10, 
     precio: 8500, 
     img: "./images/daewoo-auri.jpg",
     cantidad: 1,
     categoria: "Auriculares"},

    {nombre: "Smartwatch Colmi", 
     color: "Azul",
     id: 11, 
     precio: 25000, 
     img: "./images/colmi-reloj.jpg",
     cantidad: 1,
     categoria: "Relojes"},

    {nombre: "Smartwatch Xiaomi", 
     color: "Negro",
     id: 12, 
     precio: 35000, 
     img: "./images/xiaomi-reloj.jpg",
     cantidad: 1,
     categoria: "Relojes"},
]

let carrito = []

console.log(carrito)